base_model: "sentence-transformers/all-mpnet-base-v2"
learning_rate: 0.00002
max_length: 256
batch_size: 16
epochs: 20
evaluation_strategy: "epoch"
save_strategy: "epoch"
save_total_limit: 2
metric_for_best_model: "mse"
load_best_model_at_end: True
weight_decay: 0.01
output_dir: "./final_models/st_all_mpnet_base_v2_ft_regression"